import { PluginContract } from "../plugin-contract";
import { PluginName } from "../plugin-name";
import { TomlSnippet } from "./toml-snippet";
import type { ScaffoldOptions } from "../scaffold-options";

/**
 * The generated plugin's own `README.md`.
 *
 * It answers the three questions a scaffold cannot answer by existing: where
 * the directory has to end up, what to paste into `silo.toml`, and how to find
 * out whether it worked. Everything else — what the hooks mean, what the claim
 * grammar is — is silo's documentation, and is linked rather than copied,
 * because a copy in every scaffolded plugin is a copy that goes stale in every
 * scaffolded plugin.
 */
export class PluginReadme {
  private static readonly Docs = "https://github.com/org-quicko/silo#plugins";

  static render(options: ScaffoldOptions): string {
    return `# ${options.name}

${PluginReadme.summary(options)}

## Install

A plugin is a directory silo loads because \`silo.toml\` names it — there is no
installer and no registry. Copy this directory into your instance's data
directory:

\`\`\`sh
cp -r . <data dir>/plugins/${PluginName.installPath(options.name)}
\`\`\`

${PluginReadme.scopeNote(options)}Then name it in \`silo.toml\`:

\`\`\`toml
${TomlSnippet.render(options).trimEnd()}
\`\`\`

${TomlSnippet.OrderNote}

## Check it

\`\`\`sh
silo plugin list           # is it configured, and what does it attach to?
silo plugin info ${options.name}
silo plugin doctor         # load it the way \`serve\` would, and report failures
\`\`\`

\`doctor\` is the one that answers "would \`serve\` start?" without starting a
server. A plugin that fails to load — a missing directory, a \`silo\` range that
excludes your build, invalid config, a claim that was not granted, a declared
hook this module does not export — **refuses the start**. It is never skipped
with a warning.

## Develop

No build step and no dependencies. silo transpiles the TypeScript itself, so
\`index.ts\` is what runs.

- \`silo-api.d.ts\` is the type declaration for the \`silo:api\` virtual module.
  It has no file on disk in silo either — silo injects the module into this
  plugin's import graph before the plugin loads, which is why this package
  depends on nothing at all. The \`.d.ts\` contributes nothing at runtime; keep
  it beside \`index.ts\` for editor support.
- \`package.json#silo\` is the **manifest**, and it is static on purpose:
  \`silo plugin info\` shows an operator what this package wants *before* any of
  its code runs. A hook exported here but not declared there is never called.

${PluginReadme.kindSection(options)}
## The trust boundary

${
  options.kind === "extension"
    ? "Extension plugins run in a `Worker`. That bounds **faults** — crashes, infinite loops, memory — not **malice**: worker code holds full Bun privileges and can read the database or open a socket."
    : "Provider plugins run **in-process**, with no isolation at all: they are the storage."
} The trust boundary is the act of installing, exactly as it is for an npm
package or a VS Code extension. The claim check expresses intent and catches
mistakes; it is not a sandbox.

---

Generated by \`create-silo-plugin\`. Plugin documentation: ${PluginReadme.Docs}
`;
  }

  private static summary(options: ScaffoldOptions): string {
    if (options.kind === "provider") {
      return `A silo **provider** plugin. It implements the \`${options.port}\` port and registers the driver name \`"${options.driver}"\`, which \`silo.toml\` selects with \`[${options.port === "storage" ? "storage" : "blob_storage"}] driver = "${options.driver}"\`.`;
    }
    return `A silo **extension** plugin. It registers ${options.hooks.length === 1 ? "one hook" : `${options.hooks.length} hooks`} on the entry lifecycle and runs in a \`Worker\`, one per plugin.`;
  }

  /** Only shown for a scoped name, and only because the resolution rule is the
   *  one part of installing that surprises people. */
  private static scopeNote(options: ScaffoldOptions): string {
    if (!options.name.startsWith("@")) return "";
    return `Note the scope directory: \`${options.name}\` resolves to \`<data dir>/plugins/${options.name}/\`, not a flat \`${PluginName.unscoped(options.name)}/\`. A \`node_modules/${options.name}/\` layout is accepted too.\n\n`;
  }

  private static kindSection(options: ScaffoldOptions): string {
    if (options.kind === "provider") {
      return `### This provider

Silo constructs a provider rather than dispatching to it: \`default.create(config, silo)\`
is called once at startup, before any storage is opened, and what it returns
*is* the port. Every method in \`index.ts\` throws until you write it.

The typed interface lives in the silo repo and is not published yet. A
third-party store is only credible if it is testable — run it against
\`server/test/conformance/storage-conformance.ts\`.

The scaffold declares no \`silo.config\` schema. What a driver needs — a bucket,
an endpoint, a token — is specific to this one, so add it to
\`package.json#silo.config\` as JSON Schema: silo validates \`[plugins.config]\`
against it at startup and **refuses to start** when it does not match.

`;
    }

    const rows = options.hooks
      .map((hook) => `| \`${hook}\` | ${PluginContract.HookSummaries[hook]} |`)
      .join("\n");

    return `### This plugin's hooks

| Hook | May |
|------|-----|
${rows}

Mutation happens **before** validation, so the schema judges exactly what gets
stored. After validation a hook may reject but not rewrite. Plugins shape
\`data\`; the envelope — \`id\`, \`rev\`, \`seq\`, timestamps — belongs to silo, and
no hook can set it.

Hooks are lifecycle events, not HTTP middleware: they fire for the CRUD API and
for a plugin's own \`ctx\` writes, and deliberately **not** for \`silo import\` or
a scope copy.

`;
  }
}
