import { PluginClientSource } from "../contract/plugin-client-source";

/**
 * The bootstrap that runs inside every extension plugin's `Worker` (D31/§13.4).
 *
 * It is a **string**, not a module in this tree, and it imports nothing from
 * silo. That is forced by how silo ships: `bun build --compile` bundles the
 * host's import graph, and a `Worker` entry loaded from outside that graph
 * cannot resolve `../core/...`. Verified against a compiled binary rather than
 * assumed — a `data:` URL worker starts, and `Bun.plugin()` module registration
 * works inside the worker realm, which is what makes `silo:api` resolvable
 * there at all.
 *
 * It therefore speaks only plain JSON over `postMessage`, which is the same
 * discipline §13.4 wants for the payloads anyway.
 *
 * Since D35 the client half is **generated** from `PluginApiContract` rather
 * than written here: what the lines below hold is the invariant runtime — the
 * RPC plumbing, the query encoder, and the mapping from an error body back to
 * a throwable — and the per-operation methods are spliced in by
 * `PluginClientSource`. There is no checked-in copy of those, so they cannot
 * drift from the contract; only the `.d.ts` needs one, and it has a test.
 *
 * No template literals in the lines below: a stray `${` would interpolate at
 * the wrong level, in a file that is itself assembling source.
 */
export class WorkerSource {
  private static readonly Prelude = [
    'import { plugin } from "bun";',
    "",
    "// Errors a plugin throws to *reject* rather than to fault. Locally defined",
    "// because a class cannot cross a structured-clone boundary; the host maps",
    "// them back by `name`, which is the same reason ValidationError.is exists",
    "// on the host side.",
    "class SiloValidationError extends Error {",
    "  constructor(message, details) {",
    '    super(message); this.name = "ValidationError"; this.details = details;',
    "  }",
    "}",
    "class SiloForbiddenError extends Error {",
    '  constructor(message) { super(message); this.name = "ForbiddenError"; }',
    "}",
    "",
    'plugin({ name: "silo-api", setup(build) {',
    '  build.module("silo:api", () => ({',
    "    exports: {",
    "      defineSiloPlugin: (definition) => definition,",
    "      ValidationError: SiloValidationError,",
    "      ForbiddenError: SiloForbiddenError,",
    "    },",
    '    loader: "object",',
    "  }));",
    "}});",
    "",
    "let mod = null;",
    "let config = null;",
    "let rpcSeq = 0;",
    "const pending = new Map();",
    "",
    "// `dispatch` is the id of the hook dispatch this call is being made from,",
    "// so the host can tell which dispatch's causal chain the call belongs to.",
    "// The host reads the chain from its own record of that dispatch, never from",
    "// this message — see WorkerHost.serveRpc.",
    "const rpc = (method, args, dispatch) => new Promise((resolve, reject) => {",
    "  const id = ++rpcSeq;",
    "  pending.set(id, { resolve, reject });",
    '  self.postMessage({ t: "rpc", id, method, args, dispatch });',
    "});",
    "",
    "const revive = (e) => {",
    '  if (!e) return new Error("plugin call failed");',
    '  if (e.name === "ValidationError") return new SiloValidationError(e.message, e.details);',
    '  if (e.name === "ForbiddenError") return new SiloForbiddenError(e.message);',
    "  const err = new Error(e.message); err.name = e.name || err.name; return err;",
    "};",
    "",
    "const wire = (e) => {",
    '  const w = { name: (e && e.name) || "Error", message: (e && e.message) || String(e) };',
    "  // Only when there is one. An explicitly-undefined property is not worth",
    "  // handing to structuredClone, and omitting it keeps the wire shape to",
    "  // exactly the keys that carry meaning.",
    "  if (e && e.details) w.details = e.details;",
    "  return w;",
    "};",
    "",
    "const enc = encodeURIComponent;",
    "",
    "// An object value becomes JSON, which is how `filter` and `sort` already",
    "// reach the routes that take them — so a plugin writes the same value it",
    "// would put in a URL by hand.",
    "const search = (values) => {",
    '  if (!values) return "";',
    "  const parts = [];",
    "  for (const key of Object.keys(values)) {",
    "    const value = values[key];",
    "    if (value === undefined || value === null) continue;",
    '    const encoded = typeof value === "object" ? JSON.stringify(value) : String(value);',
    '    parts.push(enc(key) + "=" + enc(encoded));',
    "  }",
    '  return parts.length === 0 ? "" : "?" + parts.join("&");',
    "};",
    "",
    "// A refusal arrives as a status and a body, not as a throw: the route",
    "// handled it, so nothing crossed the RPC boundary as an error. Rebuilding",
    "// the throwable here is what keeps a plugin's experience identical to",
    "// before D35, when the host threw these directly.",
    "const ERROR_NAMES = {",
    '  not_found: "NotFoundError",',
    '  conflict: "ConflictError",',
    '  unauthorized: "UnauthorizedError",',
    "};",
    "",
    "const failure = (status, parsed) => {",
    "  const error = (parsed && parsed.error) || {};",
    '  const message = error.message || ("silo answered " + status);',
    '  if (error.code === "validation_failed") return new SiloValidationError(message, error.details);',
    '  if (error.code === "forbidden") return new SiloForbiddenError(message);',
    "  const err = new Error(message);",
    '  err.name = ERROR_NAMES[error.code] || "SiloApiError";',
    "  err.status = status;",
    "  err.code = error.code;",
    "  return err;",
    "};",
    "",
    "// The primitive. It reports what happened and throws only if the call",
    "// itself could not be made — a 404 is an answer, and a plugin asking",
    "// whether something exists should not need a try/catch to hear it.",
    "const buildFetch = (dispatch) => async (path, init) => {",
    "  const options = init || {};",
    "  const raw = await rpc(",
    '    "fetch",',
    '    [{ method: options.method || "GET", path, headers: options.headers, body: options.body }],',
    "    dispatch,",
    "  );",
    "  const text = () => new TextDecoder().decode(raw.body);",
    "  return {",
    "    status: raw.status,",
    "    ok: raw.status >= 200 && raw.status < 300,",
    "    headers: raw.headers,",
    "    bytes: raw.body,",
    "    // Synchronous, unlike a real Response — there is nothing left to await,",
    "    // the bytes are already here. `await response.json()` still works.",
    "    text,",
    "    json: () => { const body = text(); return body ? JSON.parse(body) : null; },",
    "  };",
    "};",
    "",
    "// What every generated method calls. JSON in, JSON out, a refusal as a",
    "// throw — the ergonomics `ctx.fetch` deliberately does not have.",
    "// A route handler's return value, normalised to the one shape the host",
    "// reads (D36). Done here rather than host-side because the ergonomic forms",
    "// only exist on this side of the clone boundary: an object is JSON, a",
    "// string is text, nothing at all is 204, and a handler that wants to set a",
    "// status says so with { status, body }.",
    "const RESPONSE_KEYS = { status: true, headers: true, body: true, json: true };",
    "",
    "const isResponseShape = (value) => {",
    "  const keys = Object.keys(value);",
    "  if (keys.length === 0) return false;",
    "  for (const key of keys) if (!RESPONSE_KEYS[key]) return false;",
    "  return true;",
    "};",
    "",
    "const respond = (value) => {",
    "  if (value === undefined || value === null) {",
    "    return { status: 204, headers: {}, body: null };",
    "  }",
    '  if (typeof value === "string") {',
    '    return { status: 200, headers: { "content-type": "text/plain; charset=utf-8" }, body: value };',
    "  }",
    '  if (typeof value !== "object") {',
    '    return { status: 200, headers: { "content-type": "application/json" }, body: JSON.stringify(value) };',
    "  }",
    "",
    "  // Not a response envelope, so it is the body. This is the common case: a",
    "  // handler returns the thing it computed.",
    "  if (!isResponseShape(value)) {",
    '    return { status: 200, headers: { "content-type": "application/json" }, body: JSON.stringify(value) };',
    "  }",
    "",
    "  const headers = Object.assign({}, value.headers);",
    "  let body = null;",
    "  if (value.json !== undefined) {",
    "    body = JSON.stringify(value.json);",
    '    if (headers["content-type"] === undefined) headers["content-type"] = "application/json";',
    "  } else if (value.body !== undefined && value.body !== null) {",
    '    body = typeof value.body === "string" ? value.body : JSON.stringify(value.body);',
    '    if (headers["content-type"] === undefined) {',
    '      headers["content-type"] = typeof value.body === "string"',
    '        ? "text/plain; charset=utf-8"',
    '        : "application/json";',
    "    }",
    "  }",
    "  const status = value.status === undefined ? (body === null ? 204 : 200) : value.status;",
    "  return { status, headers, body };",
    "};",
    "",
    "const buildCall = (fetch) => async (method, path, options) => {",
    "  const o = options || {};",
    "  const headers = {};",
    "  let body;",
    "  if (o.body !== undefined) {",
    '    headers["content-type"] = "application/json";',
    "    body = JSON.stringify(o.body);",
    "  }",
    '  if (o.rev !== undefined) headers["if-match"] = String(o.rev);',
    "",
    "  const response = await fetch(path + search(o.query), { method, headers, body });",
    "  if (response.status === 204) return null;",
    "",
    "  let parsed = null;",
    "  try {",
    "    parsed = response.json();",
    "  } catch (caught) {",
    "    if (response.ok) {",
    '      throw new Error("silo answered " + response.status + " with a body that is not JSON");',
    "    }",
    "  }",
    "  if (!response.ok) throw failure(response.status, parsed);",
    "  return parsed;",
    "};",
    "",
  ];

  private static readonly Epilogue = [
    "",
    "// Built per dispatch rather than once, so every ctx call carries the id of",
    "// the dispatch it came out of. One shared ctx could not say that, which is",
    "// why the host used to serialise dispatches to keep a single depth field",
    "// honest — and why a ctx write from a hook deadlocked.",
    "const buildCtx = (config, dispatch) => {",
    "  const fetch = buildFetch(dispatch);",
    "  return Object.assign(",
    "    {",
    "      config,",
    "      log: {",
    '        debug: (m, f) => self.postMessage({ t: "log", level: "debug", message: m, fields: f }),',
    '        info:  (m, f) => self.postMessage({ t: "log", level: "info",  message: m, fields: f }),',
    '        warn:  (m, f) => self.postMessage({ t: "log", level: "warn",  message: m, fields: f }),',
    '        error: (m, f) => self.postMessage({ t: "log", level: "error", message: m, fields: f }),',
    "      },",
    "      fetch,",
    "    },",
    "    buildApi(buildCall(fetch)),",
    "  );",
    "};",
    "",
    "self.onmessage = async (event) => {",
    "  const msg = event.data;",
    "",
    '  if (msg.t === "init") {',
    "    try {",
    "      mod = await import(Bun.pathToFileURL(msg.entry).href);",
    "      const definition = mod.default;",
    '      if (!definition || typeof definition !== "object") {',
    '        throw new Error("the default export is not a plugin definition");',
    "      }",
    "      config = msg.config;",
    "      // Hooks, routes and the runtime pair are one list here: all of them",
    "      // are functions on the same default export, named exactly as the",
    "      // manifest names them, and the host's reconcile asks the same",
    "      // question about each.",
    "      const names = msg.declared.concat(msg.routes || []);",
    '      if (msg.runtime) names.push("activate", "deactivate");',
    '      const exported = names.filter((h) => typeof definition[h] === "function");',
    '      self.postMessage({ t: "ready", hooks: exported });',
    "    } catch (caught) {",
    '      self.postMessage({ t: "init-error", error: wire(caught) });',
    "    }",
    "    return;",
    "  }",
    "",
    '  if (msg.t === "rpc-result") {',
    "    const waiter = pending.get(msg.id);",
    "    if (!waiter) return;",
    "    pending.delete(msg.id);",
    "    if (msg.ok) waiter.resolve(msg.value); else waiter.reject(revive(msg.error));",
    "    return;",
    "  }",
    "",
    '  if (msg.t === "dispatch") {',
    "    try {",
    "      const fn = mod.default[msg.hook];",
    "      const value = await fn.call(mod.default, msg.event, buildCtx(config, msg.id));",
    '      self.postMessage({ t: "result", id: msg.id, ok: true, value: value === undefined ? null : value });',
    "    } catch (caught) {",
    '      self.postMessage({ t: "result", id: msg.id, ok: false, error: wire(caught) });',
    "    }",
    "    return;",
    "  }",
    "",
    "  // A route (D36). The same ctx a hook gets, so a handler can read and",
    "  // write with the plugin's grant — and the same error path, so a handler",
    "  // that throws ValidationError produces a 400 without knowing that.",
    '  if (msg.t === "serve") {',
    "    try {",
    "      const fn = mod.default[msg.key];",
    "      const value = await fn.call(mod.default, msg.request, buildCtx(config, msg.id));",
    '      self.postMessage({ t: "result", id: msg.id, ok: true, value: respond(value) });',
    "    } catch (caught) {",
    '      self.postMessage({ t: "result", id: msg.id, ok: false, error: wire(caught) });',
    "    }",
    "    return;",
    "  }",
    "",
    "  // The runtime pair (D36). One branch for both, because they take the same",
    "  // argument and differ only in when the host sends them — and the ctx is the",
    "  // same one a hook gets, so a plugin that starts a timer in activate makes",
    "  // exactly the calls its grant allows, no more.",
    '  if (msg.t === "activate" || msg.t === "deactivate") {',
    "    try {",
    "      const fn = mod.default[msg.t];",
    "      await fn.call(mod.default, buildCtx(config, msg.id));",
    '      self.postMessage({ t: "result", id: msg.id, ok: true, value: null });',
    "    } catch (caught) {",
    '      self.postMessage({ t: "result", id: msg.id, ok: false, error: wire(caught) });',
    "    }",
    "  }",
    "};",
    "",
    'self.postMessage({ t: "booted" });',
  ];

  /** The whole bootstrap: the hand-written runtime, the generated client, and
   *  the message loop. */
  static code(): string {
    return [...WorkerSource.Prelude, ...PluginClientSource.lines(), ...WorkerSource.Epilogue].join(
      "\n"
    );
  }

  /**
   * The bootstrap as a `data:` URL.
   *
   * A URL rather than a file because `import.meta.dir` inside a compiled binary
   * points at the read-only embedded filesystem, and writing a bootstrap into
   * the data directory would put a scratch file in the one place D5 promises is
   * just the user's content. `blob:` works identically; `data:` needs no
   * lifetime management.
   */
  static url(): string {
    return "data:text/javascript;base64," + Buffer.from(WorkerSource.code(), "utf8").toString("base64");
  }
}
